### ISSUE TITLE
Create patient view

### ISSUE THREAD

**Issue by sureshHARDIYA** [sureshHARDIYA/idpt#10]
# Patient can log in 
# Patient sees his/her dashboard 
- See list of cases involved in
- See the list of modules 
- See completed modules 
- See the active tasks

# Patient can go to the task and navigate through the tasks

![image](https://user-images.githubusercontent.com/2022919/87772420-0239b100-c822-11ea-838d-c01064fba275.png)
- Can move back and forth through the `Previous` and `Next` button. 
- Has a sidebar with a list of tasks in that module. 
- The tasks are organized in the way therapists build in the builder in the backend.

**Comment by hunghkit** [comment]
can you send me web link of mockup above? @sureshHARDIYA

**Comment by sureshHARDIYA** [comment]
Acutually, its protected inside the university server and can not be shared. Its not connected to internet.
