### ISSUE TITLE
Text on the 'questionaire start page' on Android

### ISSUE THREAD

**Issue by LaurensHoogenboom** [sureshHARDIYA/idpt#16]
On the first page after you've opened a questionaire the introductoire text is hidden partially. You can tap a 'read more' button to see the whole text. This is unefficient because you have space enough to view to whole text by default.

![Screenshot_20200910_153805_com sureshkumarmukhiya psychometric](https://user-images.githubusercontent.com/49717394/92737767-b451ad00-f37b-11ea-9a7a-c43e4953dd61.jpg)

**Comment by sureshHARDIYA** [comment]
Taken care of @LaurensHoogenboom 

So closing this issue.
